galaxy_info:
  author: Shubham Girdhar
  description: your description
  company: Knoldus Inc.

  license: license (GPL-2.0-or-later, MIT, etc)

  min_ansible_version: 2.4

  galaxy_tags: []
    
dependencies: 
  - role: vm-configure
    vars:
      service_name: kafka
  - role: package-install
    vars:
      package_list:
      - openjdk-8-jdk
  - role: zookeeper
    vars:
      service_name: zookeeper
  