- name: Getting public IP address
  uri: 
    url: http://ifconfig.me/ip
    return_content: yes
  register: ip_response

- name: Configuring Kafka
  template:
    src: server.properties.j2
    dest: >-
     {{ kafka_dir }}/{{ kafka_version }}/config/server.properties
  notify: Restarting Kafka

- name: Setting up systemd
  template:
    src: kafka.service.j2
    dest: /etc/systemd/system/kafka.service
  become: yes
  become_method: sudo
  register: systemd_kafka 

- name: Reloading Systemd daemon
  systemd:
    daemon_reload: yes
  become: yes
  become_method: sudo
  when: '{{ reload_daemon_conditional }}'
