galaxy_info:
  author: Shubham Girdhar
  description: your description
  company: Knoldus Inc.

  license: license (GPL-2.0-or-later, MIT, etc)

  min_ansible_version: 2.4

  galaxy_tags: []

dependencies: []